version: "3.8"
services:

  grafana:
    image: grafana/grafana:7.3.0
    ports:
      - "3000:3000"
    depends_on:
      - postgres_grafana

    env_file:
      - .env
    tty: true
  
  postgres_grafana:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "${GF_DATABASE_EXT_PORT}:5432"

    environment:
      - POSTGRES_USER=${GF_DATABASE_USER}
      - POSTGRES_PASSWORD=${GF_DATABASE_PASSWORD}
      - POSTGRES_DB=${GF_DATABASE_NAME}

  postgres_redata:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "${REDATA_METRICS_DATABASE_EXT_PORT}:5432"

    environment:
      - POSTGRES_USER=${REDATA_METRICS_DATABASE_USER}
      - POSTGRES_PASSWORD=${REDATA_METRICS_DATABASE_PASSWORD}
      - POSTGRES_DB=${REDATA_METRICS_DATABASE_NAME}

  postgres_airflow:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "${_AIRFLOW_CONN_METADATA_DB_EXT_PORT}:5432"
    environment:
      - POSTGRES_USER=${_AIRFLOW_CONN_METADATA_DB_USER}
      - POSTGRES_PASSWORD=${_AIRFLOW_CONN_METADATA_DB_PASSWORD}
      - POSTGRES_DB=${_AIRFLOW_CONN_METADATA_DB_NAME}


  scheduler_airflow:
    image: redatateam/redata:0.0.1-alfa
    restart: always
    depends_on:
      - postgres_airflow
      - postgres_redata
      - webserver_airflow
    env_file:
      - .env
    ports:
      - "8793:8793"
    entrypoint: /usr/local/redata/scripts/redata-start.sh
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/redata-dev/redata/dags
      - PYTHONPATH=/usr/local/redata-dev
    volumes:
      - ./redata:/usr/local/redata-dev/redata
      - airflowlogs:${AIRFLOW__LOGGING__BASE_LOG_FOLDER}

  webserver_airflow:
    image: redatateam/redata:0.0.1-alfa
    hostname: webserver
    restart: always
    depends_on:
      - postgres_airflow
      - postgres_redata
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - airflowlogs:${AIRFLOW__LOGGING__BASE_LOG_FOLDER}
    entrypoint: /usr/local/redata/scripts/airflow-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  airflowlogs: {}