name: 'toy_shop'
version: '1.0.0'
config-version: 2

profile: 'toy_shop'

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]

on-run-end:
  - "{{ re_data.save_test_history(results) }}"

models:
  re_data:
    enabled: true

vars:
  re_data:alerting_z_score: 3
  re_data:monitored:
    - tables:
        - name: customers
          time_filter: joined_at
          columns:
            - first_name
            - last_name
            - age

        - name: order_items
          time_filter: added_at
          columns:
            - name
            - amount

        - name: orders
          time_filter: created_at

          metrics:
            table:
              - orders_above_100

            column:
              status:
                - distinct_values

          columns:
            - amount
            - status

        - name: companies
          time_filter: null
          columns:
            - brand_name
            - show
            - year

        - name: pending_orders
          time_filter: created_at

          metrics:
            table:
              - orders_above_100
              
          columns:
            - amount
            - status

        - name: orders_per_age
          time_filter: created_at

          metrics:
            table:
              - orders_above_100

          columns:
            - amount
            - status
            - age
        
        - name: revenue_per_age
          time_filter: created_at
          columns:
            - sum
            - age

      actively_monitored: true

  re_data:metrics_base:
    table:
      - row_count
      - freshness

    column:
      numeric:
        - min
        - max
        - avg
        - stddev
        - nulls_percent

      text:
        - min_length
        - max_length
        - avg_length
        - missing_percent
