
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'toy_shop'
version: '1.0.0'
config-version: 2

# Setup profile for re_data in your ~/.dbt/profile.yml file
profile: 'toy_shop'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
  re_data:
    enabled: true

vars:
  re_data:alerting_z_score: 3
  re_data:monitored:
    - tables:
        - name: customers
          time_filter: joined_at
          columns:
            - first_name
            - last_name
            - age

        - name: order_items
          time_filter: added_at
          columns:
            - name
            - amount

        - name: orders
          time_filter: created_at

          metrics:
            table:
              - large_orders

          columns:
            - amount
            - status

        - name: companies
          time_filter: null
          columns:
            - brand_name
            - show
            - year

        - name: pending_orders
          time_filter: created_at
          columns:
            - amount
            - status

        - name: orders_per_age
          time_filter: created_at
          columns:
            - amount
            - status
            - age
        
        - name: revenue_per_age
          time_filter: created_at
          columns:
            - sum
            - age

      actively_monitored: true

  re_data:metrics_base:
    table:
      - row_count
      - freshness

    column:
      numeric:
        - min
        - max
        - avg
        - stddev
        - nulls_percent

      text:
        - min_length
        - max_length
        - avg_length
        - missing_percent