name: 'toy_shop'
version: '1.0.0'
config-version: 2

profile: 'toy_shop'

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]

on-run-end:
  - "{{ re_data.save_test_history(results) }}"

models:
  re_data:
    enabled: true

  toy_shop:
    revenue:
      +re_data_monitored: true
      +re_data_time_filter: created_at

      orders_per_age:
        +re_data_time_filter:
        +re_data_metrics:
          table:
            - orders_above_100
          columns:
            - amount
            - status
            - age

sources:
  toy_shop_sources:
    toy_shop_customers:
      +re_data_monitored: true

seeds:
  toy_shop:
    order_items:
      +re_data_monitored: true
      +re_data_time_filter: added_at
      +re_data_columns:
        - name
        - amount
    
    orders:
      +re_data_monitored: true
      +re_data_time_filter: created_at
      +re_data_metrics:
        table:
          - orders_above_100

        column:
          status:
            - distinct_values

vars:
  re_data:alerting_z_score: 3
  re_data:metrics_base:
    table:
      - row_count
      - freshness

    column:
      numeric:
        - min
        - max
        - avg
        - stddev
        - nulls_percent

      text:
        - min_length
        - max_length
        - avg_length
        - missing_percent
