version: 2

seeds:
  - name: order_items
  - name: companies
    config:
      re_data_monitored: true
      re_data_time_filter: null
      re_data_columns:
        - brand_name
        - show
        - year

  - name: orders
    config:
      re_data_columns:
        - amount
        - status
      re_data_anomaly_detector:
        name: boxplot
        whisker_boundary_multiplier: 2.0
