version: 2

seeds:
  - name: order_items
  - name: companies
  - name: orders
    columns:
      - name: customer_id
        tests:
          - not_null

      - name: status
        tests:
          - not_null
          - accepted_values:
              values: [pending, shipped, delivered, not paid, paid]

      - name: created_at
        tests:
          - not_null

      - name: amount
        tests:
          - not_null
