version: 2

seeds:
  - name: customers
    config:
      re_data_monitored: true
      re_data_time_filter: null

  - name: orders
    config:
      re_data_monitored: true
      re_data_time_filter: time_created
      re_data_anomaly_detector:
        name: modified_z_score
        threshold: 3.5